#!/usr/bin/env ruby

/#

This script was created by Campbell Murray  <@zyx2k>
When executed it will make the system appear to hold every possible UDP port as open.

It is available for public use, modification and redistribution under the GPL license
agreement.  

NOTES: This script was tested as working on an Ubuntu 11.04 32 bit server instance
running in VirtualBox on a Fedora 16 KDE operating system.  The VM has a 4GB drive and
1 GB of RAM.  The server was installed with a GB keyboard and locale.  Apparmour and ufw
were removed and ruby1.8 installed.

This is version 0.1 for public release.
#/

# IP Tables have to be modified to send all traffic to port 1.
#Forward all UDP traffic to port 2
system('iptables -t nat -A PREROUTING -m udp -p udp -j REDIRECT --to-port 2')

require 'socket'

# Sockets to listen and respond on port 2 for UDP
s = UDPSocket.new
#Servers run forever
s.bind(0, 2)
loop {
text, sender = s.recvfrom(2)
remote_host=sender[3]
response = (text.to_i * 2).to_s
}